services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: portfolio-site
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: portfolio_backend
    restart: always
    environment:
      DATABASE_URL: "postgresql://postgres:root@postgres:5432/portfolio-site"
      PORT: 5000
      HOST: "0.0.0.0"
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    command: 
      - "sh"
      - "-c"
      - "sleep 5 && npx prisma migrate deploy && npx prisma db seed && node dist/index.js"

volumes:
  pgdata:
